#!/bin/bash
# Part of raspi-setup http://github.com/super-nathan/raspi-setup
#
# See LICENSE file for copyright and license details

if [ $(id -u) -ne 0 ]; then
  printf "\nNOTICE: the software on this Raspberry Pi has not been fully configured. Please run 'sudo raspi-setup'\n\n"
else
  sleep 4s 
  server-setup
  exec login -f root
fi
